// Generated from unique_products_and_formulas (1).xlsx, Products sheet.
// Source columns: PRODUCT NAME, ACTIVE INGREDIENT 1, CONCENTRATION 1, ACTIVE INGREDIENT 2, CONCENTRATION 2.
window.MERCBEX_PRODUCTS = [
  {
    "id": "aceman",
    "categoryId": "insecticide",
    "name": "ACEMAN",
    "active": "ACETAMIPRID",
    "concentration": "20.0 % SP",
    "active2": "",
    "concentration2": "",
    "formula": "ACETAMIPRID 20.0% SP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "acrobat",
    "categoryId": "insecticide",
    "name": "ACROBAT",
    "active": "CHLORPYRIFOS",
    "concentration": "50.0 %",
    "active2": "CYPERMETHRIN",
    "concentration2": "5.0 % EC",
    "formula": "CHLORPYRIFOS 50.0 % CYPERMETHRIN 5.0 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "acrobex",
    "categoryId": "insecticide",
    "name": "ACROBEX",
    "active": "TEBUCONAZOLE",
    "concentration": "38.39 % SC",
    "active2": "",
    "concentration2": "",
    "formula": "TEBUCONAZOLE 38.39% SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "armor",
    "categoryId": "insecticide",
    "name": "ARMOR",
    "active": "ZINEB",
    "concentration": "75.0 % WP",
    "active2": "",
    "concentration2": "",
    "formula": "ZINEB 75.0 % WP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "arrow",
    "categoryId": "insecticide",
    "name": "ARROW",
    "active": "CHLOROTHALONIL",
    "concentration": "75.0 % WP",
    "active2": "",
    "concentration2": "",
    "formula": "CHLOROTHALONIL 75.0% WP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "attacko",
    "categoryId": "insecticide",
    "name": "ATTACKO",
    "active": "PYRIPROXYFEN",
    "concentration": "10.0 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "PYRIPROXYFEN 10.0 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "axe",
    "categoryId": "insecticide",
    "name": "AXE",
    "active": "CHLOROTHALONIL",
    "concentration": "33.1 %",
    "active2": "METALAXYL-M",
    "concentration2": "3.3 % SC",
    "formula": "CHLOROTHALONIL 33.1%, METALAXYL - M 3.3% SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "azoxa",
    "categoryId": "insecticide",
    "name": "AZOXA",
    "active": "AZOXYSTROBIN",
    "concentration": "23.0 % SC",
    "active2": "",
    "concentration2": "",
    "formula": "AZOXYSTROBIN 23.0 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "bexapro",
    "categoryId": "insecticide",
    "name": "BEXAPRO",
    "active": "CYANTRANILIPROLE",
    "concentration": "10.26 % OD",
    "active2": "",
    "concentration2": "",
    "formula": "CYANTRANILIPROLE 10.26% OD",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "blaze",
    "categoryId": "insecticide",
    "name": "BLAZE",
    "active": "ABAMECTIN",
    "concentration": "1.9 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "ABAMECTIN 1.9 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "blaze-out",
    "categoryId": "insecticide",
    "name": "BLAZE-OUT",
    "active": "EMAMECTIN BENZOATE",
    "concentration": "5.0 % SG",
    "active2": "",
    "concentration2": "",
    "formula": "EMAMECTIN BENZOATE 5.0 % SG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "boromax",
    "categoryId": "insecticide",
    "name": "BOROMAX",
    "active": "BORON",
    "concentration": "",
    "active2": "",
    "concentration2": "",
    "formula": "FERTILIZERS CONTAINING BORON",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "break",
    "categoryId": "insecticide",
    "name": "BREAK",
    "active": "BIFENTHRIN",
    "concentration": "9.4 %",
    "active2": "DIAFENTHIURON",
    "concentration2": "47.0 % SC",
    "formula": "BIFENTHRIN 9.4% DIAFENTHIURON 47.0% SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "bullet",
    "categoryId": "insecticide",
    "name": "BULLET",
    "active": "CAPTAN",
    "concentration": "75 % WP",
    "active2": "",
    "concentration2": "",
    "formula": "CAPTAN 75% WP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "calcibex",
    "categoryId": "insecticide",
    "name": "CALCIBEX",
    "active": "CALCIUM",
    "concentration": "",
    "active2": "",
    "concentration2": "",
    "formula": "FERTILIZER CONTAINING CALCIUM",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "capzole",
    "categoryId": "insecticide",
    "name": "CAPZOLE",
    "active": "CAPTAN",
    "concentration": "26.9 %",
    "active2": "TEBUCONAZOLE",
    "concentration2": "6.7 % SC",
    "formula": "CAPTAN 26.9 % TEBUCONAZOLE 6.7 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "carram",
    "categoryId": "insecticide",
    "name": "CARRAM",
    "active": "CARBOXIN",
    "concentration": "37.5 %",
    "active2": "THIARAM",
    "concentration2": "37.5 % WS",
    "formula": "CARBOXIN 37.5%, THIARAM 37.5% WS",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "celbex",
    "categoryId": "insecticide",
    "name": "CELBEX",
    "active": "LAMBDA-CYHALOTHRIN",
    "concentration": "9.5 %",
    "active2": "THIAMETHOXAM",
    "concentration2": "12.6 % ZC",
    "formula": "LAMBDA- CYHALOTHRIN 9.5 % THIAMETHOXAM 12.6 % ZC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "clodex-50",
    "categoryId": "insecticide",
    "name": "CLODEX 50",
    "active": "CLOTHIANIDIN",
    "concentration": "50.0 % WDG",
    "active2": "",
    "concentration2": "",
    "formula": "CLOTHIANIDIN 50.0 % WDG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "corabex",
    "categoryId": "insecticide",
    "name": "CORABEX",
    "active": "CHLORANTRANILIPROLE",
    "concentration": "18.5 % SC",
    "active2": "",
    "concentration2": "",
    "formula": "CHLORANTRANILIPROLE 18.5 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "cozeb",
    "categoryId": "insecticide",
    "name": "COZEB",
    "active": "COPPER SULPHATE",
    "concentration": "47.15 %",
    "active2": "MANCOZEB",
    "concentration2": "30.0 % WDG",
    "formula": "COPPER SULPHATE 47.15%, MANCOZEB 30.0% WDG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "crush",
    "categoryId": "insecticide",
    "name": "CRUSH",
    "active": "FIPRONIL",
    "concentration": "40.0 %",
    "active2": "IMIDACLOPRID",
    "concentration2": "40.0 % WG",
    "formula": "FIPRONIL 40.0 % IMIDACLOPRID 40.0 % WG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "cutter",
    "categoryId": "insecticide",
    "name": "CUTTER",
    "active": "BIFENTHRIN",
    "concentration": "10 %",
    "active2": "PYRIPROXYFEN",
    "concentration2": "10 % EC",
    "formula": "BIFENTHRIN 10%, PYRIPROXYFEN 10% EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "cymex",
    "categoryId": "insecticide",
    "name": "CYMEX",
    "active": "CYMOXANIL",
    "concentration": "8.0 %",
    "active2": "MANCOZEB",
    "concentration2": "64.0 % WP",
    "formula": "CYMOXANIL 8.0 % MANCOZEB 64.0 % WP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "cypex-10",
    "categoryId": "insecticide",
    "name": "CYPEX 10",
    "active": "CYPERMETHRIN",
    "concentration": "10.0 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "CYPERMETHRIN 10.0 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "detox",
    "categoryId": "insecticide",
    "name": "DETOX",
    "active": "DIMETHOATE",
    "concentration": "30.0 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "DIMETHOATE 30.0 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "dexor",
    "categoryId": "insecticide",
    "name": "DEXOR",
    "active": "CARBENDAZIM",
    "concentration": "25 %",
    "active2": "MANCOZEB",
    "concentration2": "50 % WS",
    "formula": "CARBENDAZIM 25%, MANCOZEB 50% WS",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "difenpro",
    "categoryId": "insecticide",
    "name": "DIFENPRO",
    "active": "DIFENOCONAZOLE",
    "concentration": "13.9 %",
    "active2": "PROPICONAZOLE",
    "concentration2": "13.9 % EC",
    "formula": "DIFENOCONAZOLE 13.9% PROPICONAZOLE 13.9 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "emakill",
    "categoryId": "insecticide",
    "name": "EMAKILL",
    "active": "EMAMECTIN BENZOATE",
    "concentration": "1.9 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "EMAMECTIN BENZOATE 1.9 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "emaron",
    "categoryId": "insecticide",
    "name": "EMARON",
    "active": "EMAMECTIN BENZOATE",
    "concentration": "0.9 %",
    "active2": "NOVALURON",
    "concentration2": "5.25 % SC",
    "formula": "EMAMECTIN BENZOATE 0.9%, NOVALURON 5.25% SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "esar",
    "categoryId": "insecticide",
    "name": "ESAR",
    "active": "SPIROMESIFEN",
    "concentration": "22.9 % SC",
    "active2": "",
    "concentration2": "",
    "formula": "SPIROMESIFEN 22.9 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "exova",
    "categoryId": "insecticide",
    "name": "EXOVA",
    "active": "AZOXYSTROBIN",
    "concentration": "18.2 %",
    "active2": "DIFENOCONAZOLE",
    "concentration2": "11.4 % SC",
    "formula": "AZOXYSTROBIN 18.2 %, DIFENOCONAZOLE 11.4% SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "fe-power",
    "categoryId": "insecticide",
    "name": "FE-POWER",
    "active": "IRON",
    "concentration": "",
    "active2": "",
    "concentration2": "",
    "formula": "FERTILIZERS CONTAINING IRON",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "fenrate-20",
    "categoryId": "insecticide",
    "name": "FENRATE 20",
    "active": "FENVALEERATE",
    "concentration": "20.0 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "FENVALEERATE 20.0 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "findex",
    "categoryId": "insecticide",
    "name": "FINDEX",
    "active": "CHLORPYRIFOS",
    "concentration": "1.5 % DP",
    "active2": "",
    "concentration2": "",
    "formula": "CHLORPYRIFOS 1.5% DP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "finex",
    "categoryId": "insecticide",
    "name": "FINEX",
    "active": "DIAFENTHIURON",
    "concentration": "47.8 % SC",
    "active2": "",
    "concentration2": "",
    "formula": "DIAFENTHIURON 47.8% SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "fipmax",
    "categoryId": "insecticide",
    "name": "FIPMAX",
    "active": "FIPRONIL",
    "concentration": "0.2 %",
    "active2": "THIAMETHOXAM",
    "concentration2": "0.9 % GR",
    "formula": "FIPRONIL 0.2%, THIAMETHOXAM 0.9% GR",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "fipro-80",
    "categoryId": "insecticide",
    "name": "FIPRO 80",
    "active": "FIPRONIL",
    "concentration": "80.0 % WG",
    "active2": "",
    "concentration2": "",
    "formula": "FIPRONIL 80.0 % WG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "flex",
    "categoryId": "insecticide",
    "name": "FLEX",
    "active": "THIAMETHOXAM",
    "concentration": "30 % FS",
    "active2": "",
    "concentration2": "",
    "formula": "THIAMETHOXAM 30% FS",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "flexter",
    "categoryId": "insecticide",
    "name": "FLEXTER",
    "active": "DINOTEFURAN",
    "concentration": "20.0 % SG",
    "active2": "",
    "concentration2": "",
    "formula": "DINOTEFURAN 20.0 % SG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "full-care",
    "categoryId": "insecticide",
    "name": "FULL CARE",
    "active": "AZOXYSTROBIN",
    "concentration": "2.5 %",
    "active2": "THIAMETHOXAM",
    "concentration2": "25 %",
    "formula": "AZOXYSTROBIN 2.5%, THIAMETHOXAM 25%, THIOPHANATE METHYL 11.25% FS",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "full-core",
    "categoryId": "insecticide",
    "name": "FULL CORE",
    "active": "DIAFENTHIURON",
    "concentration": "18.0 %",
    "active2": "DINOTEFURAN",
    "concentration2": "5.0 %",
    "formula": "DIAFENTHIURON 18.0% DINOTEFURAN 5.0 % PYRIPROXYFEN 8.0 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "go-bex",
    "categoryId": "insecticide",
    "name": "GO BEX",
    "active": "THIAMETHOXAM",
    "concentration": "75 % SG",
    "active2": "",
    "concentration2": "",
    "formula": "THIAMETHOXAM 75% SG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "hammer",
    "categoryId": "insecticide",
    "name": "HAMMER",
    "active": "THIOPHANATE-METHYL",
    "concentration": "70.0 % WP",
    "active2": "",
    "concentration2": "",
    "formula": "THIOPHANATE - METHYL 70.0 % WP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "hector",
    "categoryId": "insecticide",
    "name": "HECTOR",
    "active": "ETOXAZOLE",
    "concentration": "10.0 % SC",
    "active2": "",
    "concentration2": "",
    "formula": "ETOXAZOLE 10.0 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "helmet",
    "categoryId": "insecticide",
    "name": "HELMET",
    "active": "DIFENOCONAZOLE",
    "concentration": "25.0 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "DIFENOCONAZOLE 25.0 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "hepro",
    "categoryId": "insecticide",
    "name": "HEPRO",
    "active": "IMIDACLOPRID",
    "concentration": "48 % FS",
    "active2": "",
    "concentration2": "",
    "formula": "IMIDACLOPRID 48% FS",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "hercules",
    "categoryId": "insecticide",
    "name": "HERCULES",
    "active": "HEXACONAZOLE",
    "concentration": "5.0 % SC",
    "active2": "",
    "concentration2": "",
    "formula": "HEXACONAZOLE 5.0 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "horex",
    "categoryId": "insecticide",
    "name": "HOREX",
    "active": "IMIDACLOPRID",
    "concentration": "6 %",
    "active2": "LAMBDA-CYHALOTHRIN",
    "concentration2": "4 % SL",
    "formula": "IMIDACLOPRID 6%, LAMBDA CYHALOTHRIN 4% SL",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "hyper",
    "categoryId": "insecticide",
    "name": "HYPER",
    "active": "LAMBDA-CYHALOTHRIN",
    "concentration": "5.0 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "LAMBDA - CYHALOTHRIN 5.0 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "indobex",
    "categoryId": "insecticide",
    "name": "INDOBEX",
    "active": "INDOXACARB",
    "concentration": "14.5 % SC",
    "active2": "",
    "concentration2": "",
    "formula": "INDOXACARB 14.5 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "indox",
    "categoryId": "insecticide",
    "name": "INDOX",
    "active": "PROFENOFOS",
    "concentration": "50.0 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "PROFENOFOS 50.0 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "k-power",
    "categoryId": "insecticide",
    "name": "K-POWER",
    "active": "POTASSIUM",
    "concentration": "",
    "active2": "",
    "concentration2": "",
    "formula": "FERTILIZERS CONTAINIING POTASSIUM",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "killer",
    "categoryId": "insecticide",
    "name": "KILLER",
    "active": "CARBOFURAN",
    "concentration": "3.0 % CG",
    "active2": "",
    "concentration2": "",
    "formula": "CARBOFURAN 3.0 % CG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "lotus",
    "categoryId": "insecticide",
    "name": "LOTUS",
    "active": "NOVALURON",
    "concentration": "10.0 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "NOVALURON 10.0 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "lunar",
    "categoryId": "insecticide",
    "name": "LUNAR",
    "active": "CYPERMETHRIN",
    "concentration": "25.0 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "CYPERMETHRIN 25.0 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "luxor",
    "categoryId": "insecticide",
    "name": "LUXOR",
    "active": "INDOXACARB",
    "concentration": "15.8 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "INDOXACARB 15.8% EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "lynx",
    "categoryId": "insecticide",
    "name": "LYNX",
    "active": "BUPROFEZIN",
    "concentration": "25.0 % SC",
    "active2": "",
    "concentration2": "",
    "formula": "BUPROFEZIN 25.0 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "macro",
    "categoryId": "insecticide",
    "name": "MACRO",
    "active": "CARBOXIN",
    "concentration": "37.5 %",
    "active2": "THIARAM",
    "concentration2": "37.5 % WS",
    "formula": "CARBOXIN 37.5%, THIARAM 37.5% WS",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "mag-max",
    "categoryId": "insecticide",
    "name": "MAG-MAX",
    "active": "MAGNESIUM",
    "concentration": "",
    "active2": "",
    "concentration2": "",
    "formula": "FERTILIZERS CONTAINING MAGNESIUM",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "manbex",
    "categoryId": "insecticide",
    "name": "MANBEX",
    "active": "MANGANESE",
    "concentration": "",
    "active2": "",
    "concentration2": "",
    "formula": "FERTILIZERS CONTAINING MANGANESE",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "martin",
    "categoryId": "insecticide",
    "name": "MARTIN",
    "active": "PICOXYSTROBIN",
    "concentration": "6.78 %",
    "active2": "TRICYCLAZOLE",
    "concentration2": "20.33 % SC",
    "formula": "PICOXYSTROBIN 6.78 % TRICYCLAZOLE 20.33 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "nebula",
    "categoryId": "insecticide",
    "name": "NEBULA",
    "active": "FENAZAQUIN",
    "concentration": "18.3 % SC",
    "active2": "",
    "concentration2": "",
    "formula": "FENAZAQUIN 18.3 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "neubex",
    "categoryId": "insecticide",
    "name": "NEUBEX",
    "active": "LAMBDA-CYHALOTHRIN",
    "concentration": "4.9 % CS",
    "active2": "",
    "concentration2": "",
    "formula": "LAMBDA CYHALOTHRIN 4.9 % CS",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "neutral",
    "categoryId": "insecticide",
    "name": "NEUTRAL",
    "active": "TEBUCONAZOLE",
    "concentration": "25.9 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "TEBUCONAZOLE 25.9 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "nitrobex",
    "categoryId": "insecticide",
    "name": "NITROBEX",
    "active": "NITROGEN",
    "concentration": "",
    "active2": "",
    "concentration2": "",
    "formula": "FERTILIZERS CONTAINING NITROGEN",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "nova",
    "categoryId": "insecticide",
    "name": "NOVA",
    "active": "FIPRONIL",
    "concentration": "80.0 % WG",
    "active2": "",
    "concentration2": "",
    "formula": "FIPRONIL 80.0 % WG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "novacarb",
    "categoryId": "insecticide",
    "name": "NOVACARB",
    "active": "INDOXACARB",
    "concentration": "4.5 %",
    "active2": "NOVALURON",
    "concentration2": "5.25 % SC",
    "formula": "INDOXACARB 4.5 % NOVALURON 5.25 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "orient",
    "categoryId": "insecticide",
    "name": "ORIENT",
    "active": "THIAMETHOXAM",
    "concentration": "25.0 % WG",
    "active2": "",
    "concentration2": "",
    "formula": "THIAMETHOXAM 25.0 % WG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "oxybet",
    "categoryId": "insecticide",
    "name": "OXYBET",
    "active": "OXYDEMETON-METHYL",
    "concentration": "25.0 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "OXYDEMETON METHYL 25.0 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "panther",
    "categoryId": "insecticide",
    "name": "PANTHER",
    "active": "CAPTAN",
    "concentration": "70.0 %",
    "active2": "HEXACONAZOLE",
    "concentration2": "5.0 % WP",
    "formula": "CAPTAN 70.0 % HEXACONAZOLE 5.0% WP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "phendex-2",
    "categoryId": "insecticide",
    "name": "PHENDEX 2",
    "active": "PHENTHOATE",
    "concentration": "2 % DP",
    "active2": "",
    "concentration2": "",
    "formula": "PHENTHOATE 2% DP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "phendex-50",
    "categoryId": "insecticide",
    "name": "PHENDEX 50",
    "active": "PHENTHOATE",
    "concentration": "50 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "PHENTHOATE 50% EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "phos-max",
    "categoryId": "insecticide",
    "name": "PHOS-MAX",
    "active": "PHOSPHORUS",
    "concentration": "",
    "active2": "",
    "concentration2": "",
    "formula": "FERTILIZERS CONTAINING PHOSPHORUS",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "powerbex",
    "categoryId": "insecticide",
    "name": "POWERBEX",
    "active": "TEBUCONAZOLE",
    "concentration": "50.0 %",
    "active2": "TRIFLOWXYSTROBIN",
    "concentration2": "25.0 % WG",
    "formula": "TEBUCONAZOLE 50.0 %, TRIFLOWXYSTROBIN 25.0 % WG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "powerup",
    "categoryId": "insecticide",
    "name": "POWERUP",
    "active": "AZOXYSTROBIL",
    "concentration": "4.8 %",
    "active2": "CHLOROTHALONIL",
    "concentration2": "40.0 % SC",
    "formula": "AZOXYSTROBIL 4.8% , CHLOROTHALONIL 40.0 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "pro-power",
    "categoryId": "insecticide",
    "name": "PRO POWER",
    "active": "DIAFENTHIURON",
    "concentration": "50.0 % WP",
    "active2": "",
    "concentration2": "",
    "formula": "DIAFENTHIURON 50.0 % WP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "pro-hexa",
    "categoryId": "insecticide",
    "name": "PRO-HEXA",
    "active": "HEXACONAZOLE",
    "concentration": "75.0 % WG",
    "active2": "",
    "concentration2": "",
    "formula": "HEXACONAZOLE 75.0% WG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "probex",
    "categoryId": "insecticide",
    "name": "PROBEX",
    "active": "MANCOZEB",
    "concentration": "75.0 % WP",
    "active2": "",
    "concentration2": "",
    "formula": "MANCOZEB 75.0 % WP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "prop-70",
    "categoryId": "insecticide",
    "name": "PROP 70",
    "active": "PROPINEB",
    "concentration": "70 % WP",
    "active2": "",
    "concentration2": "",
    "formula": "PROPINEB 70% WP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "punch",
    "categoryId": "insecticide",
    "name": "PUNCH",
    "active": "COPPER OXYCHLORIDE",
    "concentration": "50.0 % WP",
    "active2": "",
    "concentration2": "",
    "formula": "COPPER OXYCHLORIDE 50.0 % WP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "ra-van",
    "categoryId": "insecticide",
    "name": "RA-VAN",
    "active": "AZOXYSTROBIN",
    "concentration": "11.0 %",
    "active2": "TEBUCONAZOLE",
    "concentration2": "18.3 % SC",
    "formula": "AZOXYSTROBIN 11.0 %, TEBUCONAZOLE 18.3 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "robex",
    "categoryId": "insecticide",
    "name": "ROBEX",
    "active": "MANCOZEB",
    "concentration": "64.0 %",
    "active2": "METALAXYL",
    "concentration2": "8.0 % WP",
    "formula": "MANCOZEB 64.0 % METALAXYL 8.0 % WP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "roxx",
    "categoryId": "insecticide",
    "name": "ROXX",
    "active": "THIACLOPRID",
    "concentration": "21.7 % SC",
    "active2": "",
    "concentration2": "",
    "formula": "THIACLOPRID 21.7 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "saaf",
    "categoryId": "insecticide",
    "name": "SAAF",
    "active": "CARBENDAZIM",
    "concentration": "50.0 % WP",
    "active2": "",
    "concentration2": "",
    "formula": "CARBENDAZIM 50.0 % WP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "safari",
    "categoryId": "insecticide",
    "name": "SAFARI",
    "active": "IMIDACLOPRID",
    "concentration": "70.0 % WG",
    "active2": "",
    "concentration2": "",
    "formula": "IMIDACLOPRID 70.0 % WG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "sceptor",
    "categoryId": "insecticide",
    "name": "SCEPTOR",
    "active": "AZOXYSTROBIN",
    "concentration": "4.8 %",
    "active2": "CHLOROTHALONIL",
    "concentration2": "40.0 % SC",
    "formula": "AZOXYSTROBIN 4.8 % CHLOROTHALONIL 40.0 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "seal",
    "categoryId": "insecticide",
    "name": "SEAL",
    "active": "TOLFENPYRAD",
    "concentration": "15.0 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "TOLFENPYRAD 15.0% EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "secure",
    "categoryId": "insecticide",
    "name": "SECURE",
    "active": "FIPRONIL",
    "concentration": "0.3 % GR",
    "active2": "",
    "concentration2": "",
    "formula": "FIPRONIL 0.3 % GR",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "shield",
    "categoryId": "insecticide",
    "name": "SHIELD",
    "active": "QUINALPHOS",
    "concentration": "25.0 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "QUINALPHOS 25.0 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "shine",
    "categoryId": "insecticide",
    "name": "SHINE",
    "active": "IMIDACLOPRID",
    "concentration": "48 % FS",
    "active2": "",
    "concentration2": "",
    "formula": "IMIDACLOPRID 48% FS",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "shoot",
    "categoryId": "insecticide",
    "name": "SHOOT",
    "active": "IMIDACLOPRID",
    "concentration": "30.5 % SC",
    "active2": "",
    "concentration2": "",
    "formula": "IMIDACLOPRID 30.5 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "sixer-75",
    "categoryId": "insecticide",
    "name": "SIXER 75",
    "active": "CARBENDAZIM",
    "concentration": "12.0 %",
    "active2": "MANCOZEB",
    "concentration2": "63.0 % WP",
    "formula": "CARBENDAZIM 12.0 % MANCOZEB 63.0% WP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "star",
    "categoryId": "insecticide",
    "name": "STAR",
    "active": "DINOTEFURAN",
    "concentration": "15 %",
    "active2": "PYMETROZINE",
    "concentration2": "45 % WG",
    "formula": "DINOTEFURAN 15%,PYMETROZINE 45% WG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "stop",
    "categoryId": "insecticide",
    "name": "STOP",
    "active": "DIMETHOATE",
    "concentration": "30.0 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "DIMETHOATE 30.0 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "storm",
    "categoryId": "insecticide",
    "name": "STORM",
    "active": "DINOTEFURAN",
    "concentration": "70.0 % WG",
    "active2": "",
    "concentration2": "",
    "formula": "DINOTEFURAN 70.0 % WG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "stream",
    "categoryId": "insecticide",
    "name": "STREAM",
    "active": "PROPICONAZOLE",
    "concentration": "25.0 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "PROPICONAZOLE 25.0 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "sul-bex",
    "categoryId": "insecticide",
    "name": "SUL-BEX",
    "active": "SULPHUR",
    "concentration": "",
    "active2": "",
    "concentration2": "",
    "formula": "FERTILIZERS CONTAINING SULPHUR",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "sulfomax",
    "categoryId": "insecticide",
    "name": "SULFOMAX",
    "active": "SULPHUR",
    "concentration": "80.0 % WP",
    "active2": "",
    "concentration2": "",
    "formula": "SULPHUR 80.0% WP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "supronil",
    "categoryId": "insecticide",
    "name": "SUPRONIL",
    "active": "FIPRONIL",
    "concentration": "5.0 % SC",
    "active2": "",
    "concentration2": "",
    "formula": "FIPRONIL 5.0 % SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "tetracin",
    "categoryId": "insecticide",
    "name": "TETRACIN",
    "active": "STREPTOMYCIN SULFATE",
    "concentration": "90 %",
    "active2": "TETRACYCLINE HYDROCHLORIDE",
    "concentration2": "10 % SP",
    "formula": "STREPTOMYCIN SULFATE 90%, TETRACYCLINE HYDROCHLORIDE 10% SP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "topper",
    "categoryId": "insecticide",
    "name": "TOPPER",
    "active": "DELTAMETHRIN",
    "concentration": "2.8 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "DELTAMETHRIN 2.8 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "trident",
    "categoryId": "insecticide",
    "name": "TRIDENT",
    "active": "AZOXYSTROBIN",
    "concentration": "8.3 %",
    "active2": "MANCOZEB",
    "concentration2": "66.7 % WG",
    "formula": "AZOXYSTROBIN 8.3 % MANCOZEB 66.7 % WG",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "trivex",
    "categoryId": "insecticide",
    "name": "TRIVEX",
    "active": "TRICHODERMA VIRIDE",
    "concentration": "1 % WP",
    "active2": "",
    "concentration2": "",
    "formula": "TRICHODERMA VIRIDE 1% WP",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "veron",
    "categoryId": "insecticide",
    "name": "VERON",
    "active": "CHLORANTRANILIPROLE",
    "concentration": "9.3 %",
    "active2": "LAMBDA-CYHALOTHRIN",
    "concentration2": "4.6 % ZC",
    "formula": "CHLORANTRANILIPROLE 9.3 %, LAMBDA-CYHALOTHRIN 4.6% ZC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "voltex",
    "categoryId": "insecticide",
    "name": "VOLTEX",
    "active": "CARBENDAZIM",
    "concentration": "25.0 %",
    "active2": "FLUSILAZOLE",
    "concentration2": "12.5 % SE",
    "formula": "CARBENDAZIM 25.0 % FLUSILAZOLE 12.5 % SE",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "winner",
    "categoryId": "insecticide",
    "name": "WINNER",
    "active": "CHLORPYIFOS",
    "concentration": "20.0 % EC",
    "active2": "",
    "concentration2": "",
    "formula": "CHLORPYIFOS 20.0 % EC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "wipe",
    "categoryId": "insecticide",
    "name": "WIPE",
    "active": "IMIDACLOPRID",
    "concentration": "17.8 % SL",
    "active2": "",
    "concentration2": "",
    "formula": "IMIDACLOPRID 17.8 % SL",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "wrap",
    "categoryId": "insecticide",
    "name": "WRAP",
    "active": "PICOXYSTROBIN",
    "concentration": "22.52 % SC",
    "active2": "",
    "concentration2": "",
    "formula": "PICOXYSTROBIN 22.52% SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "zebro",
    "categoryId": "insecticide",
    "name": "ZEBRO",
    "active": "SPINOSAD",
    "concentration": "45 % SC",
    "active2": "",
    "concentration2": "",
    "formula": "SPINOSAD 45% SC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  },
  {
    "id": "zinc-max",
    "categoryId": "insecticide",
    "name": "ZINC-MAX",
    "active": "ZINC",
    "concentration": "",
    "active2": "",
    "concentration2": "",
    "formula": "FERTILIZERS CONTAINING ZINC",
    "mockup": "assets/mockups/aceman-single-bottle-white-studio-base.png"
  }
];
